apiVersion: v1
kind: Service
metadata:
  name: voyage-analytics-api
  namespace: voyage-analytics
spec:
  selector:
    app: voyage-analytics-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
